### ISSUE TITLE
Runtime issue: assigning -1 into NSUInteger

### ISSUE THREAD

**Issue by xhruso00** [pixelspark/mbtablegrid#80]
Xcode 15.4.
macOS14.5

-1 is outside the range of representable values of type 'unsigned long'

https://github.com/pixelspark/mbtablegrid/blob/7f7645b1b5cf98faf4e2df2c4e5614cde16aafa1/MBTableGrid.m#L1714

(lldb) po contentRect
(origin = (x = -56, y = -25), size = (width = 516, height = 1))
(lldb) po NSMaxY(contentRect)
-24
(lldb) po rowHeight
20
(lldb) po ceil(NSMaxY(contentRect)/rowHeight)
-1
(lldb) po MIN(numberOfRows - 1, ceil(NSMaxY(contentRect)/rowHeight))
-1

Version 15.4 (15F31d)
macOS 14.5 (23F79)

**Comment by xhruso00** [comment]
NOTE: The most elegant/simple solution with `NSIntersectsRect` cannot be used as this method is called by the `MBTableGridHeaderView`, `MBTableGridContentView`, `MBTableGridFooterView` and `NSRect contentRect = [self convertRect:rect toView:self.contentView];` will cause `MBTableGridHeaderView` to NOT intersect.

**Comment by pixelspark** [comment]
This is closed by #81, right? Thanks!
